# Generated by Django 5.0.4 on 2024-04-24 09:34

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('experiment_name', models.CharField(max_length=100)),
                ('experiment_status', models.BooleanField(default=False)),
                ('experiment_key', models.CharField(max_length=100)),
                ('experiment_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('slot_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experiments', to_field='experiment_code')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', to_field='email')),
            ],
        ),
    ]
