# Generated by Django 3.2.18 on 2024-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.CharField(max_length=100, unique=True)),
                ('exp_name', models.CharField(max_length=100)),
                ('exp_status', models.BooleanField()),
                ('exp_que', models.IntegerField()),
                ('exp_key', models.CharField(max_length=100)),
            ],
        ),
    ]
