# Generated by Django 5.0.4 on 2024-04-24 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraccount",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RemoveField(model_name="useraccount", name="name",),
        migrations.AddField(
            model_name="useraccount",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="first_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
