# Generated by Django 3.2.18 on 2024-04-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='experiment_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='slotbookings',
            name='experiment_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experiments', to_field='experiment_name'),
        ),
    ]
